# Generated by Django 3.1.4 on 2020-12-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg', models.CharField(max_length=50, verbose_name='Telegram')),
                ('cash', models.CharField(max_length=50, verbose_name='Размер оплаты')),
                ('tex_zad', models.TextField(verbose_name='О проекте')),
            ],
        ),
    ]
